{{- if and .Values.swr.username .Values.swr.password }}
apiVersion: v1
kind: Secret
metadata:
  name: swr-secret
  namespace: {{ include "awx.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.imageRegistry .Values.swr.username .Values.swr.password (printf "%s:%s" .Values.swr.username .Values.swr.password | b64enc) | b64enc }}
{{- end }}
